-- 烹饪模块数据库表结构

-- 分类表
CREATE TABLE `cooking_category` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类编号',
  `name` varchar(100) NOT NULL COMMENT '分类名称',
  `description` varchar(500) DEFAULT NULL COMMENT '分类描述',
  `icon` varchar(255) DEFAULT NULL COMMENT '分类图标',
  `image` varchar(255) DEFAULT NULL COMMENT '分类图片',
  `parent_id` bigint NOT NULL DEFAULT '0' COMMENT '父分类ID',
  `type` tinyint NOT NULL COMMENT '分类类型（1菜谱分类 2食材分类）',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（0禁用 1启用）',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_type` (`type`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='烹饪分类表';

-- 菜谱表
CREATE TABLE `cooking_recipe` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '菜谱编号',
  `name` varchar(100) NOT NULL COMMENT '菜谱名称',
  `description` text COMMENT '菜谱描述',
  `cover_image` varchar(255) DEFAULT NULL COMMENT '菜谱封面图片',
  `category_id` bigint NOT NULL COMMENT '菜系分类ID',
  `source_url` varchar(500) DEFAULT NULL COMMENT '菜谱来源URL',
  `source` varchar(100) DEFAULT NULL COMMENT '菜谱来源',
  `difficulty` tinyint NOT NULL DEFAULT '2' COMMENT '难度等级（1简单 2中等 3困难 4专家级）',
  `prep_time` int DEFAULT NULL COMMENT '准备时间（分钟）',
  `cook_time` int DEFAULT NULL COMMENT '烹饪时间（分钟）',
  `total_time` int DEFAULT NULL COMMENT '总时间（分钟）',
  `servings` int DEFAULT NULL COMMENT '份数',
  `calories` decimal(8,2) DEFAULT NULL COMMENT '热量（卡路里）',
  `protein` decimal(8,2) DEFAULT NULL COMMENT '蛋白质（克）',
  `fat` decimal(8,2) DEFAULT NULL COMMENT '脂肪（克）',
  `carbohydrates` decimal(8,2) DEFAULT NULL COMMENT '碳水化合物（克）',
  `fiber` decimal(8,2) DEFAULT NULL COMMENT '纤维（克）',
  `sugar` decimal(8,2) DEFAULT NULL COMMENT '糖分（克）',
  `sodium` decimal(8,2) DEFAULT NULL COMMENT '钠（毫克）',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态（0草稿 1已发布 2审核中 3已拒绝 4已禁用）',
  `creator_id` bigint DEFAULT NULL COMMENT '创建者用户ID',
  `view_count` int NOT NULL DEFAULT '0' COMMENT '浏览次数',
  `favorite_count` int NOT NULL DEFAULT '0' COMMENT '收藏次数',
  `rating` decimal(3,2) NOT NULL DEFAULT '0.00' COMMENT '评分（1-5星）',
  `rating_count` int NOT NULL DEFAULT '0' COMMENT '评分次数',
  `tags` json DEFAULT NULL COMMENT '标签（JSON数组）',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_category_id` (`category_id`),
  KEY `idx_status` (`status`),
  KEY `idx_creator_id` (`creator_id`),
  KEY `idx_source_url` (`source_url`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='菜谱表';

-- 食材表
CREATE TABLE `cooking_ingredient` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '食材编号',
  `name` varchar(100) NOT NULL COMMENT '食材名称',
  `description` text COMMENT '食材描述',
  `image` varchar(255) DEFAULT NULL COMMENT '食材图片',
  `category_id` bigint NOT NULL COMMENT '食材分类ID',
  `unit` varchar(10) NOT NULL COMMENT '单位（如：克、毫升、个等）',
  `calories_per_100g` decimal(8,2) DEFAULT NULL COMMENT '每100g热量（卡路里）',
  `protein_per_100g` decimal(8,2) DEFAULT NULL COMMENT '每100g蛋白质（克）',
  `fat_per_100g` decimal(8,2) DEFAULT NULL COMMENT '每100g脂肪（克）',
  `carbohydrates_per_100g` decimal(8,2) DEFAULT NULL COMMENT '每100g碳水化合物（克）',
  `fiber_per_100g` decimal(8,2) DEFAULT NULL COMMENT '每100g纤维（克）',
  `sugar_per_100g` decimal(8,2) DEFAULT NULL COMMENT '每100g糖分（克）',
  `sodium_per_100g` decimal(8,2) DEFAULT NULL COMMENT '每100g钠（毫克）',
  `seasons` json DEFAULT NULL COMMENT '季节性（JSON数组）',
  `storage_advice` varchar(200) DEFAULT NULL COMMENT '存储建议',
  `shelf_life` int DEFAULT NULL COMMENT '保质期（天）',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（0禁用 1启用）',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_category_id` (`category_id`),
  KEY `idx_status` (`status`),
  KEY `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='食材表';

-- 菜谱食材关联表
CREATE TABLE `cooking_recipe_ingredient` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '关联编号',
  `recipe_id` bigint NOT NULL COMMENT '菜谱ID',
  `ingredient_id` bigint NOT NULL COMMENT '食材ID',
  `amount` decimal(10,2) NOT NULL COMMENT '用量',
  `unit` varchar(10) NOT NULL COMMENT '单位',
  `required` tinyint NOT NULL DEFAULT '1' COMMENT '是否必需（0可选 1必需）',
  `remark` varchar(100) DEFAULT NULL COMMENT '备注（如：切丝、切块等处理方式）',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_recipe_id` (`recipe_id`),
  KEY `idx_ingredient_id` (`ingredient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='菜谱食材关联表';

-- 烹饪步骤表
CREATE TABLE `cooking_cooking_step` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '步骤编号',
  `recipe_id` bigint NOT NULL COMMENT '菜谱ID',
  `step_order` int NOT NULL COMMENT '步骤顺序',
  `title` varchar(100) DEFAULT NULL COMMENT '步骤标题',
  `description` text NOT NULL COMMENT '步骤描述',
  `image` varchar(255) DEFAULT NULL COMMENT '步骤图片',
  `cooking_time` int DEFAULT NULL COMMENT '烹饪时间（分钟）',
  `temperature` decimal(5,2) DEFAULT NULL COMMENT '烹饪温度（摄氏度）',
  `heat_level` varchar(20) DEFAULT NULL COMMENT '火候（如：大火、中火、小火）',
  `tips` text DEFAULT NULL COMMENT '技巧提示',
  `notes` text DEFAULT NULL COMMENT '注意事项',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（0禁用 1启用）',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_recipe_id` (`recipe_id`),
  KEY `idx_step_order` (`step_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='烹饪步骤表';

-- 初始化分类数据
INSERT INTO `cooking_category` (`name`, `description`, `type`, `parent_id`, `sort`, `status`) VALUES
('荤菜', '包含肉类的菜品', 1, 0, 1, 1),
('素菜', '不含肉类的蔬菜菜品', 1, 0, 2, 1),
('水产', '鱼类、虾类等水产菜品', 1, 0, 3, 1),
('早餐', '适合早餐时间的菜品', 1, 0, 4, 1),
('主食', '米饭、面条等主食类', 1, 0, 5, 1),
('汤与粥', '各种汤类和粥类', 1, 0, 6, 1),
('饮料', '各种饮品', 1, 0, 7, 1),
('甜品', '甜点和甜品', 1, 0, 8, 1),
('半成品加工', '半成品食材的加工方法', 1, 0, 9, 1),
('酱料和其它材料', '调料和辅助材料', 1, 0, 10, 1),
('肉类', '各种肉类食材', 2, 0, 1, 1),
('蔬菜', '各种蔬菜食材', 2, 0, 2, 1),
('水产', '鱼虾蟹等水产食材', 2, 0, 3, 1),
('调料', '各种调味料', 2, 0, 4, 1),
('其他', '其他类型食材', 2, 0, 5, 1);
